### ISSUE TITLE
Epic: Geolocation enrichment and filtering with OpenStreetMap data

### ISSUE THREAD

**Issue by Yolgie** [boudicca-events/boudicca.events#302]
This ticket is an epic and should be split into multiple subtickets like for example:

- [ ] enriching events by linking them to openstreetmap
- [ ] enriching events by adding "correct" addresses, coordinates, ...
- [ ] enriching events by adding other structured openstreetmap data or discuss how to handle osm data in other ways
- [ ] expanding the search to be able to search by location or osm data
- [ ] expanding the search/filter to be able to search by proximity to an address or the user location
- [ ] <optional> expanding the search/filter to be able to search by walking distance
- [ ] <optional> expanding the search/filter to be able to search by public transport distance

**Comment by Yolgie** [comment]
Maybe also talk to @dmorawetz and triply for support in the public transport part :)
